{
 "title": "Lodestar",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Node summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(time() - lodestar_genesis_time) / 12",
     "legendFormat": "clock slot"
    },
    { "expr": "beacon_head_slot", "legendFormat": "head slot" },
    {
     "expr": "changes(process_start_time_seconds[5m])",
     "legendFormat": "process restart"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(lodestar_peers_by_direction)"
    }
   ]
  },
  {
   "title": "Head Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_head_slot" }
   ]
  },
  {
   "title": "Finalized Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_finalized_epoch" }
   ]
  },
  {
   "title": "Slots / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(beacon_head_slot[2m])" }
   ]
  },
  {
   "title": "CPU %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_heap_bytes" }
   ]
  },
  {
   "title": "Uptime since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds*1000"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodestar_sync_status" }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodestar_version", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "Lodestar version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodestar_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "NodeJS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_version_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Peer count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lodestar_peers_by_direction", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Slots / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_head_slot[$__rate_interval])",
     "legendFormat": "lodestar"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clock drift",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(time() - lodestar_genesis_time) / 12 - lodestar_clock_slot",
       "legendFormat": "clock drift"
      }
     ]
    },
    {
     "title": "Sync status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "lodestar_sync_status", "legendFormat": "status" }
     ]
    },
    {
     "title": "head drift",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "lodestar_clock_slot - beacon_head_slot",
       "legendFormat": "clock drift"
      }
     ]
    },
    {
     "title": "-",
     "type": "text",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "targets": [
      { "expr": "lodestar_sync_status", "legendFormat": "status" }
     ]
    }
   ]
  },
  {
   "title": "VM Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Space Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_used_bytes",
       "legendFormat": "{{space}}"
      }
     ]
    },
    {
     "title": "External Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "nodejs_external_memory_bytes", "legendFormat": "nodejs_external_memory_bytes" }
     ]
    },
    {
     "title": "Process heap bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "process_heap_bytes" }
     ]
    },
    {
     "title": "GC pause time rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(nodejs_gc_pause_seconds_total[$__rate_interval])",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "GC reclaimed bytes (per interval)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(nodejs_gc_reclaimed_bytes_total[$__rate_interval])",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "GC runs (per interval)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nodejs_gc_runs_total[$__rate_interval])",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Active requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "nodejs_active_requests", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "event loop lag" }
     ]
    },
    {
     "title": "Active Handles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "nodejs_active_handles", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "CPU usage % (Lodestar only)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_user_seconds_total[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus scrape duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(scrape_duration_seconds[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Lodestar prom-client is down",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "1-up" }
     ]
    }
   ]
  },
  {
   "title": "Beacon state transition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Epoch transition avg time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_stfn_epoch_transition_seconds_sum[$__rate_interval])/delta(lodestar_stfn_epoch_transition_seconds_count[$__rate_interval])",
       "legendFormat": "epoch transition"
      }
     ]
    },
    {
     "title": "Process block avg time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_stfn_process_block_seconds_sum[$__rate_interval])/delta(lodestar_stfn_process_block_seconds_count[$__rate_interval])",
       "legendFormat": "process block time"
      }
     ]
    },
    {
     "title": "Epoch transition utilization rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(lodestar_stfn_epoch_transition_seconds_sum[$__rate_interval])",
       "legendFormat": "process block time"
      }
     ]
    },
    {
     "title": "Process block utilization rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(lodestar_stfn_process_block_seconds_sum[$__rate_interval])",
       "legendFormat": "process block time"
      }
     ]
    },
    {
     "title": "Epoch transitions / slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "12*rate(lodestar_stfn_epoch_transition_seconds_count[$__rate_interval])",
       "legendFormat": "process block time"
      }
     ]
    },
    {
     "title": "process block / slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "12*rate(lodestar_stfn_process_block_seconds_count[$__rate_interval])",
       "legendFormat": "process block time"
      }
     ]
    }
   ]
  },
  {
   "title": "BLS worker pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "BLS thread pool utilization rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(lodestar_bls_thread_pool_success_time_seconds_sum[$__rate_interval])",
       "legendFormat": "{{workerId}}"
      }
     ]
    },
    {
     "title": "BLS thread pool job wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_bls_thread_pool_queue_job_wait_time_seconds_sum[$__rate_interval])/delta(lodestar_bls_thread_pool_queue_job_wait_time_seconds_count[$__rate_interval])",
       "legendFormat": "pool"
      }
     ]
    },
    {
     "title": "BLS thread pool signature set verification time / set",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(delta(lodestar_bls_thread_pool_success_time_seconds_sum[$__rate_interval]))/sum(delta(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$__rate_interval]))",
       "legendFormat": "pool"
      }
     ]
    },
    {
     "title": "BLS thread pool average job group size",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "delta(lodestar_bls_thread_pool_jobs_started_total[$__rate_interval])/delta(lodestar_bls_thread_pool_job_groups_started_total[$__rate_interval])",
       "legendFormat": "pool"
      }
     ]
    },
    {
     "title": "BLS thread pool average signature sets per job",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "delta(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$__rate_interval])/(delta(lodestar_bls_thread_pool_jobs_started_total[$__rate_interval])>0)",
       "legendFormat": "pool"
      }
     ]
    }
   ]
  },
  {
   "title": "Block processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block processor queue - Utilization rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(lodestar_block_processor_queue_job_time_seconds_sum[$__rate_interval])",
       "legendFormat": "block_processor"
      }
     ]
    },
    {
     "title": "Block processor queue - Jobs / slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "12*rate(lodestar_block_processor_queue_job_time_seconds_count[$__rate_interval])",
       "legendFormat": "block_processor"
      }
     ]
    },
    {
     "title": "Block processor queue - Job time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_block_processor_queue_job_time_seconds_sum[$__rate_interval])/delta(lodestar_block_processor_queue_job_time_seconds_count[$__rate_interval])",
       "legendFormat": "block_processor"
      }
     ]
    },
    {
     "title": "Block processor queue - Dropped jobs %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "delta(lodestar_block_processor_queue_dropped_jobs_total[$__rate_interval])/(delta(lodestar_block_processor_queue_job_time_seconds_count[$__rate_interval])+delta(lodestar_block_processor_queue_dropped_jobs_total[$__rate_interval]))",
       "legendFormat": "block_processor"
      }
     ]
    },
    {
     "title": "Block processor queue - Job wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_block_processor_queue_job_wait_time_seconds_sum[$__rate_interval])/delta(lodestar_block_processor_queue_job_wait_time_seconds_count[$__rate_interval])",
       "legendFormat": "block_processor"
      }
     ]
    },
    {
     "title": "Block processor queue - Length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lodestar_block_processor_queue_length",
       "legendFormat": "block_processor"
      }
     ]
    }
   ]
  },
  {
   "title": "Regen queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Regen queue - Utilization ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(lodestar_regen_queue_job_time_seconds_sum[$__rate_interval])",
       "legendFormat": "regen_queue"
      }
     ]
    },
    {
     "title": "Regen queue - Jobs / slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "12*rate(lodestar_regen_queue_job_time_seconds_count[$__rate_interval])",
       "legendFormat": "regen_queue"
      }
     ]
    },
    {
     "title": "Regen queue - Job time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_regen_queue_job_time_seconds_sum[$__rate_interval])/delta(lodestar_regen_queue_job_time_seconds_count[$__rate_interval])",
       "legendFormat": "regen_queue"
      }
     ]
    },
    {
     "title": "Regen queue - Dropped jobs %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "delta(lodestar_regen_queue_dropped_jobs_total[$__rate_interval])/(delta(lodestar_regen_queue_job_time_seconds_count[$__rate_interval])+delta(lodestar_regen_queue_dropped_jobs_total[$__rate_interval]))",
       "legendFormat": "regen_queue"
      }
     ]
    },
    {
     "title": "Regen queue - Job wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_regen_queue_job_wait_time_seconds_sum[$__rate_interval])/delta(lodestar_regen_queue_job_wait_time_seconds_count[$__rate_interval])",
       "legendFormat": "regen_queue"
      }
     ]
    },
    {
     "title": "Regen queue - Length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "lodestar_regen_queue_length", "legendFormat": "regen_queue" }
     ]
    }
   ]
  },
  {
   "title": "Fork-Choice Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "find head avg time (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(beacon_fork_choice_find_head_seconds_sum[$__rate_interval])/delta(beacon_fork_choice_find_head_seconds_count[$__rate_interval])",
       "legendFormat": "find head"
      }
     ]
    },
    {
     "title": "Total findHead Requests vs changed heads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "delta(beacon_fork_choice_changed_head_total[$__rate_interval])",
       "legendFormat": "Changed Heads"
      },
      {
       "expr": "delta(beacon_fork_choice_requests_total[$__rate_interval])",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "find head / slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "12*rate(beacon_fork_choice_find_head_seconds_count[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Fork Choice Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "beacon_fork_choice_errors_total"
      }
     ]
    },
    {
     "title": "find head utilization rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(beacon_fork_choice_find_head_seconds_sum[$__rate_interval])",
       "legendFormat": "process  time"
      }
     ]
    },
    {
     "title": "Reorgs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "beacon_fork_choice_reorg_total" }
     ]
    }
   ]
  },
  {
   "title": "Gossip validation queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossip validation queue - Utilization rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(lodestar_gossip_validation_queue_job_time_seconds_sum[$__rate_interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Gossip validation queue - Processed jobs / slot",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "12*rate(lodestar_gossip_validation_queue_job_time_seconds_count[$__rate_interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Gossip validation queues - Job time (async)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "delta(lodestar_gossip_validation_queue_job_time_seconds_sum[$__rate_interval])/delta(lodestar_gossip_validation_queue_job_time_seconds_count[$__rate_interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Gossip validation queue - Dropped jobs %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "delta(lodestar_gossip_validation_queue_dropped_jobs_total[$__rate_interval])/(delta(lodestar_gossip_validation_queue_job_time_seconds_count[$__rate_interval])+delta(lodestar_gossip_validation_queue_dropped_jobs_total[$__rate_interval]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Gossip validation queues - Job wait time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "delta(lodestar_gossip_validation_queue_job_wait_time_seconds_sum[$__rate_interval])/delta(lodestar_gossip_validation_queue_job_wait_time_seconds_count[$__rate_interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Gossip validation queues - Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "lodestar_gossip_validation_queue_length",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST API response times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "delta(lodestar_api_rest_response_time_seconds_sum[$__rate_interval])/delta(lodestar_api_rest_response_time_seconds_count[$__rate_interval])",
       "legendFormat": "{{operationId}}"
      }
     ]
    },
    {
     "title": "REST API queries / slot",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "12*rate(lodestar_api_rest_response_time_seconds_count[$__rate_interval])",
       "legendFormat": "{{operationId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Peer stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goodbyes received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(lodestar_peer_goodbye_received[$__rate_interval])>0",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Peer connected event",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(lodestar_peer_connected[$__rate_interval])>0",
       "legendFormat": "{{direction}}"
      }
     ]
    },
    {
     "title": "Goodbyes sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(lodestar_peer_goodbye_sent[$__rate_interval])>0",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Peer disconnected event",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(lodestar_peer_disconnected[$__rate_interval])>0",
       "legendFormat": "{{direction}}"
      }
     ]
    },
    {
     "title": "Total unique peers connected to",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "lodestar_peers_total_unique_connected",
       "legendFormat": "peers"
      }
     ]
    },
    {
     "title": "Peer connect events offset (must be 0-1)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "lodestar_peer_connected - lodestar_peer_disconnected - lodestar_peers_by_direction",
       "legendFormat": "{{direction}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mesh Peers per Topic",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lodestar_gossip_mesh_peers_by_type{type!~\"beacon_attestation\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Beacon Attestation Mesh Peers per Subnet",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lodestar_gossip_mesh_peers_by_beacon_attestation_subnet",
       "legendFormat": "{{subnet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ReqResp Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing requests rate (stacked)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(beacon_reqresp_outgoing_requests_total[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Incoming requests rate (stacked)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "rate(beacon_reqresp_incoming_requests_total[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Outgoing requests error rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "delta(beacon_reqresp_outgoing_requests_error_total[$__rate_interval])/(delta(beacon_reqresp_outgoing_requests_total[$__rate_interval]) > 0)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Incoming requests error rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "delta(beacon_reqresp_incoming_requests_error_total[$__rate_interval])/(delta(beacon_reqresp_incoming_requests_total[$__rate_interval])>0)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Dial errors rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "rate(beacon_reqresp_dial_errors_total[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "DB disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB - reads / sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(lodestar_db_reads[$__rate_interval])",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "DB - writes / sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(lodestar_db_writes[$__rate_interval])",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Production Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attempts vs successes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "increase(beacon_block_production_requests_total[$__rate_interval])",
       "legendFormat": "total"
      },
      {
       "expr": "increase(beacon_block_production_successes_total[$__rate_interval])",
       "legendFormat": "success"
      }
     ]
    },
    {
     "title": "Block production avg time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(beacon_block_production_seconds_sum[$__rate_interval])/delta(beacon_block_production_seconds_count[$__rate_interval])"
      }
     ]
    }
   ]
  }
 ]
}